<?php


$posts_arr = [
  [
    "id" => "1",
    "title" => "5 Tips for an Epic White Beard",
    "author" => "Mike Lawson",
    "date" => "Dec 05, 2023",
    "description" => "we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.",
    "content" => "
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier. </p>
      <div class='img'></div>
      <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.</p>
      "
  ],
  [
    "id" => "2",
    "title" => "The Ultimate Guide to Beards and Ingrown Hairs",
    "author" => "Wil Mouradian",
    "date" => "Feb 22, 2018",
    "description" => "we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.",
    "content" => "
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier. </p>
      <div class='img'></div>
      <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.</p>
      "
  ],
  [
    "id" => "3",
    "title" => "How To Stop Picking Your Beard and Other Bad Habits",
    "author" => "Urban Beardsman",
    "date" => "Mar 30, 2016",
    "description" => "we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.",
    "content" => "
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier. </p>
      <div class='img'></div>
      <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.</p>
      "
  ],
  [
    "id" => "4",
    "title" => "Best Beards of Star Wars",
    "author" => "Urban Beardsman",
    "date" => "Mar 30, 2016",
    "description" => "we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.",
    "content" => "
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier. </p>
      <div class='img'></div>
      <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus quod sed dolore, harum nostrum possimus illo corrupti ratione ipsa doloribus mollitia aspernatur dicta sequi cupiditate eius vel maxime, aperiam adipisci! 1. FIND THE RIGHT WHITE BEARD LENGTH AND SHAPE The longer and more out of control your white beard gets, the more you will have people referring to you as Santa Claus, Merlin, and Gandalf. There’s no way around this — it’s human nature. On the flip side, going too short can also be an issue. As your hair loses its pigmentation, it becomes finer. This can leave you with more holes and patches in your beard than you’re accustomed to or a beard that is easy to see through. The sweet spot for a white beard tends to be between two and six inches — long enough to provide complete, even coverage but not so long that you enter wizard territory. Hard angles are your friend when it comes to shaping a white beard. As we age, our bodies and faces soften and become rounder. You can fight back by opting for a beard style with sharper lines, such as a spade shape or boxed beard. 2. DOUBLE DOWN ON SOFTENING There’s a common misconception that gray hair is coarser than pigmented hair. But your silver hair is actually finer in texture than it was when you were younger. It only feels coarse and wiry because white hair tends to be drier.</p>
      "
  ],
];
